In [1]:
# Import standard libraries that you may use most times
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

print("TensorFlow version:", tf.__version__)

2023-03-24 00:46:06.771268: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


TensorFlow version: 2.11.0


In [2]:
l1 = tf.keras.layers.SimpleRNN(units=4, return_sequences=True, return_state=True, activation="linear")


In [3]:
# inputs: A 3D tensor, with shape [batch, timesteps, feature]
# np.random.random([1, 4, 2]).astype(np.float32) 
x = np.array(
    [[  [0 , 1 ],
        [1 , 3 ],
        [2 , 1 ],
        [2 , 0 ]],

     [  [1 , 1],
        [2 , 3 ],
        [1 , 1 ],
        [0 , 1 ]],
    ]).astype(np.float32)
print(x, x.shape)
yhs, final_state = l1(x[0, np.newaxis])
yhs, final_state

[[[0. 1.]
  [1. 3.]
  [2. 1.]
  [2. 0.]]

 [[1. 1.]
  [2. 3.]
  [1. 1.]
  [0. 1.]]] (2, 4, 2)


2023-03-24 00:46:22.099405: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


(<tf.Tensor: shape=(1, 4, 4), dtype=float32, numpy=
 array([[[-0.71201634, -0.7456565 , -0.0841279 ,  0.19091058],
         [-1.8633313 , -2.6850853 , -1.9883252 ,  0.72654545],
         [ 0.37084705, -2.6974735 , -4.425899  ,  2.19847   ],
         [ 3.9040022 , -3.9778283 , -3.5249481 ,  2.6152525 ]]],
       dtype=float32)>,
 <tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[ 3.9040022, -3.9778283, -3.5249481,  2.6152525]], dtype=float32)>)

In [4]:
l1.weights

[<tf.Variable 'simple_rnn/simple_rnn_cell/kernel:0' shape=(2, 4) dtype=float32, numpy=
 array([[ 0.422287  , -0.5546026 , -0.81824684, -0.32641673],
        [-0.71201634, -0.7456565 , -0.0841279 ,  0.19091058]],
       dtype=float32)>,
 <tf.Variable 'simple_rnn/simple_rnn_cell/recurrent_kernel:0' shape=(4, 4) dtype=float32, numpy=
 array([[ 0.37514734, -0.6271418 ,  0.32896778, -0.59811205],
        [ 0.09892067,  0.49630967,  0.862344  ,  0.01594465],
        [-0.2846764 ,  0.47527102, -0.22606516, -0.8012312 ],
        [ 0.87660635,  0.3667252 , -0.3115086 , -0.00603324]],
       dtype=float32)>,
 <tf.Variable 'simple_rnn/simple_rnn_cell/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]

In [5]:
a0 = np.array([[0,0,1,1], [0,1,1,0]]).astype(np.float32)
w0 = np.array([[0,0,1,1], [0,1,1,0], [1,1,1,0], [0,1,1,0]]).astype(np.float32)
b0 = np.array([0., 0., 0., 0.]).astype(np.float32)
l1.set_weights([a0, w0, b0]) 
l1.weights

[<tf.Variable 'simple_rnn/simple_rnn_cell/kernel:0' shape=(2, 4) dtype=float32, numpy=
 array([[0., 0., 1., 1.],
        [0., 1., 1., 0.]], dtype=float32)>,
 <tf.Variable 'simple_rnn/simple_rnn_cell/recurrent_kernel:0' shape=(4, 4) dtype=float32, numpy=
 array([[0., 0., 1., 1.],
        [0., 1., 1., 0.],
        [1., 1., 1., 0.],
        [0., 1., 1., 0.]], dtype=float32)>,
 <tf.Variable 'simple_rnn/simple_rnn_cell/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]

In [6]:
yhs, final_state = l1(x[0, np.newaxis])
yhs, final_state

(<tf.Tensor: shape=(1, 4, 4), dtype=float32, numpy=
 array([[[ 0.,  1.,  1.,  0.],
         [ 1.,  5.,  6.,  1.],
         [ 6., 13., 16.,  3.],
         [16., 32., 40.,  8.]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[16., 32., 40.,  8.]], dtype=float32)>)

In [ ]:
# inputs: A 3D tensor, with shape [batch, timesteps, feature]
inputs = np.random.random([32, 10, 8]).astype(np.float32)
simple_rnn = tf.keras.layers.SimpleRNN(4)

output = simple_rnn(inputs)  # The output has shape `[32, 4]`.

simple_rnn = tf.keras.layers.SimpleRNN(
    4, return_sequences=True, return_state=True)

# whole_sequence_output has shape `[32, 10, 4]`.
# final_state has shape `[32, 4]`.
whole_sequence_output, final_state = simple_rnn(inputs)