In [1]:
%reload_ext autoreload
import colabexts
from colabexts.jcommon import *

jpath=os.path.dirname(colabexts.__file__)
jcom = f'{jpath}/jcommon.ipynb'
%run $jcom

# From Scratch

In [66]:
def sigmoid (z): 
    return  1 / (1 + np.exp(-z))

def Xentropy(Y, A):
    m = Y.shape[-1]
    cost = (-1 / m) * np.sum(Y * np.log(A) + (1 - Y) * (np.log(1 - A)))
    return  cost

def forward(w, b, X, Y, activation=sigmoid):
    m = X.shape[1]
    
    A = activation(np.dot(w.T, X) + b) 
    cost = Xentropy(Y, A)
    return cost, A

def backward(A, X, Y):
    m = X.shape[1]
    dw = (1 / m) * np.dot(X, (A - Y).T)
    db = (1 / m) * np.sum(A - Y)

    return dw, db

def optim(w, b, X, Y, lr=0.1):
    costs = []
    
    cost, A = forward(w, b, X, Y)
    dw, db  = backward(A, X, Y)

    w = w - lr * dw
    b = b - lr * db    
    
    return w, b, cost

def init(dim):
    w = np.random.rand(dim)
    b = 0
    return w, b

w, b = init(2)
X, Y = np.array([[1,2], [3,4]]), np.array([[1, 0]])

cost=np.inf
print ( f"Start: Cost:{cost:.4} {w} {b}")
for i in range(10):
    w, b, cost = optim(w,b, X,Y)
    print ( f"{i:03}. Cost:{cost:.4} {w} {b}")


Start: Cost:inf [0.93674874 0.36772907] 0
000. Cost:1.751 [[0.84591026 0.27689059]
 [0.76082545 0.19180577]] -0.042542408862974675
001. Cost:3.319 [[0.74900299 0.21406883]
 [0.56919565 0.08155928]] -0.1136160385046125
002. Cost:2.689 [[0.65589012 0.16930452]
 [0.38735119 0.01275884]] -0.16999989131967008
003. Cost:2.208 [[ 0.57030902  0.13836567]
 [ 0.22425835 -0.02458857]] -0.2119600445559798
004. Cost:1.863 [[ 0.49732757  0.11604384]
 [ 0.09143876 -0.04239355]] -0.2396206919443316
005. Cost:1.65 [[ 0.44041631  0.09857813]
 [-0.00388149 -0.04920683]] -0.2534989724709614
006. Cost:1.542 [[ 0.39839569  0.08362697]
 [-0.06510806 -0.05035596]] -0.256200931801772
007. Cost:1.495 [[ 0.36710115  0.06984624]
 [-0.10203318 -0.04890685]] -0.25140129787685195
008. Cost:1.473 [[ 0.34260814  0.05653672]
 [-0.12364636 -0.0464589 ]] -0.24208265263930326
009. Cost:1.461 [[ 0.32225387  0.04336963]
 [-0.13599517 -0.0437669 ]] -0.23015038241585872


In [ ]:
from sympy import * 

x, y, i = symbols("x y i")
e1 = 3 * x ** 2 + y**(i)
e2 = (1/(1+exp(-i)) )
e1, e2
e2

In [ ]:
z='$3 x^{2} + y^{i}$'
f=latex(expr)

z value is {{ z }} ==  {{z}}

$3 x^{2} + y^{i}$

OK

In [ ]:
diff(e2)

# Jacobian

In [20]:
import numpy as np
import tensorflow as tf
#from tensorflow.keras.models import Sequential
#from tensorflow.keras.layers import Dense

print(tf.__version__, tf.keras.__version__)

tf.random.set_seed(0)
x = tf.random.normal([7, 3])
layer = tf.keras.layers.Dense(2, activation=tf.nn.relu, input_shape=(7,3,1))
y = layer(x)

# ~~~ Set custom weights
wts0=( np.array([[0.5, 0.1], [0.1, 0.5], [0, 0]]),  np.array([0,0]) )
layer.set_weights(wts0)

with tf.GradientTape(persistent=True) as tape:
    y = layer(x)

y.shape

2.4.3 2.4.0


TensorShape([7, 2])

In [21]:
y


<tf.Tensor: shape=(7, 2), dtype=float32, numpy=
array([[0.13514608, 0.6289093 ],
       [0.19590005, 0.9297324 ],
       [0.        , 0.        ],
       [0.57275546, 0.37099153],
       [1.1100389 , 0.7828406 ],
       [0.        , 0.        ],
       [0.16187313, 0.22445773]], dtype=float32)>

In [22]:
x

<tf.Tensor: shape=(7, 3), dtype=float32, numpy=
array([[ 0.01950879,  1.2539169 ,  0.6854247 ],
       [ 0.0207366 ,  1.8553175 , -0.8524053 ],
       [ 0.01949384, -1.6901307 ,  2.0456352 ],
       [ 1.0386608 ,  0.5342509 ,  0.3535879 ],
       [ 1.9863974 ,  1.1684017 ,  0.4402932 ],
       [-1.6585735 , -1.1999398 ,  1.3715065 ],
       [ 0.24371162,  0.40017313, -0.73295605]], dtype=float32)>

In [11]:
layer.get_weights()

[array([[-0.38111752,  0.865276  ],
        [-0.8746438 , -0.797227  ],
        [-0.00296402, -0.6831708 ]], dtype=float32),
 array([0., 0.], dtype=float32)]

# Jacobian

In [73]:
import numpy as np
import tensorflow as tf

print(tf.__version__, tf.keras.__version__)

tf.random.set_seed(0)
x = tf.Variable([[1., 2.], [2.,1.]])
d = tf.Variable(0.0)

with tf.GradientTape(persistent=True) as tape:
    y = (x+d)**2

dy_dx = tape.jacobian(y, d)
y.shape, dy_dx.shape

2.4.3 2.4.0


(TensorShape([2, 2]), TensorShape([2, 2]))

In [74]:
dy_dx

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 4.],
       [4., 2.]], dtype=float32)>