In [1]:
# Import standard libraries that you may use most times
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.4.3


In [66]:
l1 = tf.keras.layers.SimpleRNN(units=4, return_sequences=True, return_state=True, activation="linear")


In [67]:
# inputs: A 3D tensor, with shape [batch, timesteps, feature]
# np.random.random([1, 4, 2]).astype(np.float32) 
x = np.array(
    [[  [0 , 1 ],
        [1 , 3 ],
        [2 , 1 ],
        [2 , 0 ]],

     [  [1 , 1],
        [2 , 3 ],
        [1 , 1 ],
        [0 , 1 ]],
    ]).astype(np.float32)
print(x, x.shape)
yhs, final_state = l1(x[0, np.newaxis])
yhs, final_state

[[[0. 1.]
  [1. 3.]
  [2. 1.]
  [2. 0.]]

 [[1. 1.]
  [2. 3.]
  [1. 1.]
  [0. 1.]]] (2, 4, 2)


(<tf.Tensor: shape=(1, 4, 4), dtype=float32, numpy=
 array([[[-0.10598612, -0.9480407 ,  0.7599113 ,  0.96044517],
         [-0.8094461 , -3.7728183 ,  3.7216744 ,  2.6788685 ],
         [-0.76816225, -4.0299606 ,  5.4051733 , -1.5885403 ],
         [ 3.6604376 , -4.421138  ,  4.3602686 , -1.8053069 ]]],
       dtype=float32)>,
 <tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[ 3.6604376, -4.421138 ,  4.3602686, -1.8053069]], dtype=float32)>)

In [68]:
l1.weights

[<tf.Variable 'simple_rnn_11/simple_rnn_cell_11/kernel:0' shape=(2, 4) dtype=float32, numpy=
 array([[ 0.03224039, -0.37920523,  0.6904471 ,  0.92401433],
        [-0.10598612, -0.9480407 ,  0.7599113 ,  0.96044517]],
       dtype=float32)>,
 <tf.Variable 'simple_rnn_11/simple_rnn_cell_11/recurrent_kernel:0' shape=(4, 4) dtype=float32, numpy=
 array([[-0.3266722 , -0.7860833 , -0.31949604,  0.4162696 ],
        [-0.07385284,  0.38113594,  0.28120703,  0.87761253],
        [ 0.30142444, -0.47727275,  0.82483435, -0.03165685],
        [-0.8927341 ,  0.09496891,  0.37214643, -0.23561338]],
       dtype=float32)>,
 <tf.Variable 'simple_rnn_11/simple_rnn_cell_11/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]

In [69]:
a0 = np.array([[0,0,1,1], [0,1,1,0]]).astype(np.float32)
w0 = np.array([[0,0,1,1], [0,1,1,0], [1,1,1,0], [0,1,1,0]]).astype(np.float32)
b0 = np.array([0., 0., 0., 0.]).astype(np.float32)
l1.set_weights([a0, w0, b0]) 
l1.weights

[<tf.Variable 'simple_rnn_11/simple_rnn_cell_11/kernel:0' shape=(2, 4) dtype=float32, numpy=
 array([[0., 0., 1., 1.],
        [0., 1., 1., 0.]], dtype=float32)>,
 <tf.Variable 'simple_rnn_11/simple_rnn_cell_11/recurrent_kernel:0' shape=(4, 4) dtype=float32, numpy=
 array([[0., 0., 1., 1.],
        [0., 1., 1., 0.],
        [1., 1., 1., 0.],
        [0., 1., 1., 0.]], dtype=float32)>,
 <tf.Variable 'simple_rnn_11/simple_rnn_cell_11/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]

In [70]:
yhs, final_state = l1(x[0, np.newaxis])
yhs, final_state

(<tf.Tensor: shape=(1, 4, 4), dtype=float32, numpy=
 array([[[ 0.,  1.,  1.,  0.],
         [ 1.,  5.,  6.,  1.],
         [ 6., 13., 16.,  3.],
         [16., 32., 40.,  8.]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[16., 32., 40.,  8.]], dtype=float32)>)

In [17]:
# inputs: A 3D tensor, with shape [batch, timesteps, feature]
inputs = np.random.random([32, 10, 8]).astype(np.float32)
simple_rnn = tf.keras.layers.SimpleRNN(4)

output = simple_rnn(inputs)  # The output has shape `[32, 4]`.

simple_rnn = tf.keras.layers.SimpleRNN(
    4, return_sequences=True, return_state=True)

# whole_sequence_output has shape `[32, 10, 4]`.
# final_state has shape `[32, 4]`.
whole_sequence_output, final_state = simple_rnn(inputs)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 0.62279004,  0.04022525,  0.3555005 ,  0.29787636],
       [ 0.90325713, -0.03884618,  0.9596978 ,  0.78025365],
       [ 0.3446492 ,  0.8397548 ,  0.6342527 , -0.47363558],
       [-0.6701257 , -0.40392202,  0.48921576,  0.6713644 ]],
      dtype=float32)>