In [1]:
# Import standard libraries that you may use most times
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.4.3


In [28]:
l1 = tf.keras.layers.SimpleRNN(4, return_sequences=True, return_state=True, activation="linear")


In [59]:
# inputs: A 3D tensor, with shape [batch, timesteps, feature]
# np.random.random([1, 4, 2]).astype(np.float32) 
x = np.array(
    [[  [0 , 1 ],
        [1 , 3 ],
        [2 , 1 ],
        [2 , 0 ]],

     [  [1 , 1],
        [2 , 3 ],
        [1 , 1 ],
        [0 , 1 ]],
    ]).astype(np.float32)
print(x, x.shape)
yhs, final_state = l1(x)
yhs, final_state

[[[0. 1.]
  [1. 3.]
  [2. 1.]
  [2. 0.]]

 [[1. 1.]
  [2. 3.]
  [1. 1.]
  [0. 1.]]] (2, 4, 2)


ValueError: Input 0 of layer simple_rnn_9 is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: (4, 2)

In [55]:
l1.weights

[<tf.Variable 'simple_rnn_9/simple_rnn_cell_9/kernel:0' shape=(2, 4) dtype=float32, numpy=
 array([[0., 0., 1., 1.],
        [0., 1., 1., 0.]], dtype=float32)>,
 <tf.Variable 'simple_rnn_9/simple_rnn_cell_9/recurrent_kernel:0' shape=(4, 4) dtype=float32, numpy=
 array([[0., 0., 1., 1.],
        [0., 1., 1., 0.],
        [1., 1., 1., 0.],
        [0., 1., 1., 0.]], dtype=float32)>,
 <tf.Variable 'simple_rnn_9/simple_rnn_cell_9/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]

In [53]:
a0 = np.array([[0,0,1,1], [0,1,1,0]]).astype(np.float32)
w0 = np.array([[0,0,1,1], [0,1,1,0], [1,1,1,0], [0,1,1,0]]).astype(np.float32)
b0 = np.array([0., 0., 0., 0.]).astype(np.float32)
l1.set_weights([a0, w0, b0])
l1.weights

[<tf.Variable 'simple_rnn_9/simple_rnn_cell_9/kernel:0' shape=(2, 4) dtype=float32, numpy=
 array([[0., 0., 1., 1.],
        [0., 1., 1., 0.]], dtype=float32)>,
 <tf.Variable 'simple_rnn_9/simple_rnn_cell_9/recurrent_kernel:0' shape=(4, 4) dtype=float32, numpy=
 array([[0., 0., 1., 1.],
        [0., 1., 1., 0.],
        [1., 1., 1., 0.],
        [0., 1., 1., 0.]], dtype=float32)>,
 <tf.Variable 'simple_rnn_9/simple_rnn_cell_9/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]

In [17]:
# inputs: A 3D tensor, with shape [batch, timesteps, feature]
inputs = np.random.random([32, 10, 8]).astype(np.float32)
simple_rnn = tf.keras.layers.SimpleRNN(4)

output = simple_rnn(inputs)  # The output has shape `[32, 4]`.

simple_rnn = tf.keras.layers.SimpleRNN(
    4, return_sequences=True, return_state=True)

# whole_sequence_output has shape `[32, 10, 4]`.
# final_state has shape `[32, 4]`.
whole_sequence_output, final_state = simple_rnn(inputs)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 0.62279004,  0.04022525,  0.3555005 ,  0.29787636],
       [ 0.90325713, -0.03884618,  0.9596978 ,  0.78025365],
       [ 0.3446492 ,  0.8397548 ,  0.6342527 , -0.47363558],
       [-0.6701257 , -0.40392202,  0.48921576,  0.6713644 ]],
      dtype=float32)>