## Dataset

In [1]:
# Import standard libraries that you may use most times
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import random

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
mpl.rcParams['figure.figsize'] = (16, 5)
mpl.rcParams['axes.grid'] = False
# -------------------------------------------------------------------------
# 1. Some book keeping    
print("TensorFlow version:", tf.__version__)

#See also: https://mobiarch.wordpress.com/2020/11/13/preparing-time-series-data-for-rnn-in-tensorflow/


2023-01-23 02:20:23.506077: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


TensorFlow version: 2.11.0


# Read the data 

In [19]:
def getCSV(file = '../data/jena_climate_2009_2016.csv.zip', nrows=1024*1024):
    df = pd.read_csv(file, nrows = nrows)
    return df

def getTest():
    values = np.array([
         [1, 10, 100,  -1, -1],
         [2, 20, 200,  -2, -2],
         [3, 30, 300,  -3, -3],
         [4, 40, 400,  -4, -4],
         [5, 50, 500,  -5, -5],
         [6, 60, 600,  -6, -6],
         [7, 70, 700,  -7, -7],
         [8, 80, 800,  -8, -8],
         [9, 90, 900,  -9, -9],
         [10,100,1000, -10, -10],
         [11,110,1100, -11, -11],
         [12,120,1200, -12, -12],
    ])
    return values;

def printDS(ds, len=4):
    i = 0
    for inputs, targets in ds:
        print(inputs.numpy() , targets.numpy())
        i += 1
        if ( i >= len):
            break;

# Prepare the data

In [22]:
values = getTest()
window_len = 5
output_len = 2
batch_size = 2

def tsdata(ds, label_slice, window_len, output_len=1, batch_size=1):
    ds = ds.window(window_len + output_len, shift=1, drop_remainder=True)
    ds = ds.flat_map(lambda x: x).batch(window_len + output_len)
     
    def feature_label(x):
        return x[:window_len], x[window_len:,label_slice]

    ds = ds.map(feature_label)

    return ds.batch(batch_size)
 
ds = tf.data.Dataset.from_tensor_slices(values)

#ds = tf.data.experimental.CsvDataset("../stock_data.csv", header=True, record_defaults=[int()]*15)
#ds = ds.map(lambda *items: tf.stack(items))

ds = tsdata(ds, slice(0,3), window_len=window_len, output_len=output_len, batch_size=batch_size)
printDS(ds, 1)

[[[  1  10 100  -1  -1]
  [  2  20 200  -2  -2]
  [  3  30 300  -3  -3]
  [  4  40 400  -4  -4]
  [  5  50 500  -5  -5]]

 [[  2  20 200  -2  -2]
  [  3  30 300  -3  -3]
  [  4  40 400  -4  -4]
  [  5  50 500  -5  -5]
  [  6  60 600  -6  -6]]] [[[  6  60 600]
  [  7  70 700]]

 [[  7  70 700]
  [  8  80 800]]]
