# Coding Exercise Part 1: Tensor Operations with NumPy and PyTorch

### Objective:
Familiarize yourself with tensor operations using both NumPy and PyTorch.

### 1. Creating 2D tensors/arrays with random numbers


Using [NumPy](https://numpy.org/doc/stable/reference/generated/numpy.array.html):

In [1]:
import numpy as np

# Create a 5x5 array with random numbers between 0 and 1
numpy_array = np.random.rand(5, 5)
print("NumPy Array:\n", numpy_array)

NumPy Array:
 [[0.21610752 0.79095168 0.62356931 0.85165165 0.04141243]
 [0.33722833 0.04313671 0.50434124 0.02292856 0.28568838]
 [0.22131103 0.14133876 0.90145664 0.56367609 0.9857611 ]
 [0.55001886 0.4507039  0.53358814 0.86748687 0.17906216]
 [0.34478257 0.99697606 0.44255562 0.69986001 0.64253593]]


Using [PyTorch](https://pytorch.org/docs/stable/tensors.html):

In [2]:
import torch

# Create a 5x5 tensor with random numbers between 0 and 1
pytorch_tensor = torch.rand(5, 5)
print("PyTorch Tensor:\n", pytorch_tensor)

PyTorch Tensor:
 tensor([[0.8187, 0.2760, 0.4316, 0.9928, 0.8475],
        [0.6278, 0.1480, 0.6747, 0.4759, 0.4459],
        [0.6903, 0.6497, 0.0370, 0.4295, 0.0387],
        [0.5680, 0.5104, 0.8442, 0.2759, 0.9592],
        [0.3978, 0.6704, 0.4820, 0.6038, 0.0386]])


### 2. Performing Tensor Operations


a. Compute Mean and Standard Deviation

In [3]:
# NumPy
numpy_mean = numpy_array.mean()
numpy_std  = numpy_array.std()
print(f"NumPy Array - Mean: {numpy_mean}, Standard Deviation: {numpy_std}")

# PyTorch
pytorch_mean = pytorch_tensor.mean().item()
pytorch_std = pytorch_tensor.std().item()
print(f"PyTorch Tensor - Mean: {pytorch_mean}, Standard Deviation: {pytorch_std}")

NumPy Array - Mean: 0.489525181645125, Standard Deviation: 0.2971017991767556
PyTorch Tensor - Mean: 0.5173778533935547, Standard Deviation: 0.27578213810920715


b. Element-wise Multiplication

In [4]:
# Create another 5x5 tensor/array with random numbers between 1 and 2
numpy_array_2    = 1 + np.random.rand(5, 5)
pytorch_tensor_2 = 1 + torch.rand(5, 5)

# Element-wise multiplication
numpy_product   = numpy_array * numpy_array_2
pytorch_product = pytorch_tensor * pytorch_tensor_2

print("Element-wise Multiplication - NumPy:\n", numpy_product)
print("Element-wise Multiplication - PyTorch:\n", pytorch_product)

Element-wise Multiplication - NumPy:
 [[0.32126531 1.35161137 1.06370762 1.55665844 0.06566626]
 [0.6662874  0.07834781 0.61078603 0.0317227  0.28767085]
 [0.41951642 0.28164582 1.53434579 0.61944825 1.86016557]
 [0.98795356 0.85592683 0.67935912 0.94728397 0.20125087]
 [0.5397936  1.65696546 0.55926947 1.04680693 0.67607394]]
Element-wise Multiplication - PyTorch:
 tensor([[1.1364, 0.5270, 0.7122, 1.2091, 1.2885],
        [1.0851, 0.1807, 0.8710, 0.7083, 0.6218],
        [1.2321, 1.0601, 0.0724, 0.6440, 0.0452],
        [0.7443, 0.6616, 1.1730, 0.3429, 1.7377],
        [0.6900, 1.1529, 0.5470, 0.9949, 0.0596]])


c. [Matrix Multiplication](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) with its Transpose

In [5]:
# Matrix multiplication
numpy_matmul   = numpy_array @ numpy_array.T
pytorch_matmul = pytorch_tensor @ pytorch_tensor.T

print("Matrix Multiplication with Transpose - NumPy:\n", numpy_matmul)
print("Matrix Multiplication with Transpose - PyTorch:\n", pytorch_matmul)

Matrix Multiplication with Transpose - NumPy:
 [[1.78817123 0.45284655 1.24261823 1.55428943 1.76168001]
 [0.45284655 0.45208737 0.82991577 0.54508053 0.5820876 ]
 [1.24261823 0.82991577 2.17103497 1.33192785 1.64404152]
 [1.55428943 0.54508053 1.33192785 1.57496778 1.59729359]
 [1.76168001 0.5820876  1.64404152 1.59729359 2.21134821]]
Matrix Multiplication with Transpose - PyTorch:
 tensor([[2.6368, 1.6965, 1.2197, 2.0571, 1.3509],
        [1.6965, 1.2966, 0.7762, 1.5607, 0.9788],
        [1.2197, 0.7762, 1.0860, 0.9105, 0.9888],
        [2.0571, 1.5607, 0.9105, 2.2919, 1.1786],
        [1.3509, 0.9788, 0.9888, 1.1786, 1.2060]])


d. Sum of All Elements

In [6]:
# Sum of all elements
numpy_sum   = numpy_array.sum()
pytorch_sum = pytorch_tensor.sum().item()

print(f"Sum of all elements - NumPy: {numpy_sum}")
print(f"Sum of all elements - PyTorch: {pytorch_sum}")

Sum of all elements - NumPy: 12.238129541128124
Sum of all elements - PyTorch: 12.934446334838867


### 3. Conversion between PyTorch and NumPy

In [7]:
# Convert PyTorch tensor to NumPy array
converted_to_numpy = pytorch_tensor.numpy()
print("Converted PyTorch Tensor to NumPy:\n", converted_to_numpy)

# Convert NumPy array to PyTorch tensor
converted_to_pytorch = torch.from_numpy(numpy_array)
print("Converted NumPy Array to PyTorch Tensor:\n", converted_to_pytorch)

Converted PyTorch Tensor to NumPy:
 [[0.81874096 0.27595508 0.4315793  0.9928426  0.847535  ]
 [0.6277569  0.14803827 0.67472994 0.47594714 0.44588184]
 [0.6903079  0.6496798  0.03697646 0.42952776 0.03874415]
 [0.5679885  0.5103542  0.84419394 0.2758745  0.9592183 ]
 [0.39779222 0.67037314 0.48196238 0.6038312  0.03861481]]
Converted NumPy Array to PyTorch Tensor:
 tensor([[0.2161, 0.7910, 0.6236, 0.8517, 0.0414],
        [0.3372, 0.0431, 0.5043, 0.0229, 0.2857],
        [0.2213, 0.1413, 0.9015, 0.5637, 0.9858],
        [0.5500, 0.4507, 0.5336, 0.8675, 0.1791],
        [0.3448, 0.9970, 0.4426, 0.6999, 0.6425]], dtype=torch.float64)


### 4. Reshaping and Slicing Tensors


a. Create a tensor of shape (10, 2) filled with random numbers.
Reshape it to (5, 4) and (2, 10).

Using [NumPy](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html):

In [8]:
# Reshaping
numpy_tensor = np.random.rand(10, 2)
print("Original NumPy Tensor:\n", numpy_tensor)

reshaped_5_4 = numpy_tensor.reshape(5, 4)
print("\nReshaped to (5, 4):\n", reshaped_5_4)

reshaped_2_10 = numpy_tensor.reshape(2, 10)
print("\nReshaped to (2, 10):\n", reshaped_2_10)

Original NumPy Tensor:
 [[0.26244164 0.61501034]
 [0.30508858 0.05159495]
 [0.45442122 0.23996299]
 [0.30682827 0.77474526]
 [0.89803755 0.02539723]
 [0.79199277 0.63733757]
 [0.01111514 0.01344511]
 [0.8165614  0.01370879]
 [0.33731656 0.81972702]
 [0.37982776 0.1094478 ]]

Reshaped to (5, 4):
 [[0.26244164 0.61501034 0.30508858 0.05159495]
 [0.45442122 0.23996299 0.30682827 0.77474526]
 [0.89803755 0.02539723 0.79199277 0.63733757]
 [0.01111514 0.01344511 0.8165614  0.01370879]
 [0.33731656 0.81972702 0.37982776 0.1094478 ]]

Reshaped to (2, 10):
 [[0.26244164 0.61501034 0.30508858 0.05159495 0.45442122 0.23996299
  0.30682827 0.77474526 0.89803755 0.02539723]
 [0.79199277 0.63733757 0.01111514 0.01344511 0.8165614  0.01370879
  0.33731656 0.81972702 0.37982776 0.1094478 ]]


Using [PyTorch](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html):

In [9]:
# Reshaping
pytorch_tensor = torch.rand(10, 2)
print("Original PyTorch Tensor:\n", pytorch_tensor)

reshaped_5_4 = pytorch_tensor.view(5, 4)
print("\nReshaped to (5, 4):\n", reshaped_5_4)

reshaped_2_10 = pytorch_tensor.view(2, 10)
print("\nReshaped to (2, 10):\n", reshaped_2_10)

Original PyTorch Tensor:
 tensor([[0.9532, 0.5883],
        [0.5531, 0.3851],
        [0.6855, 0.5814],
        [0.7410, 0.8357],
        [0.1497, 0.1235],
        [0.1092, 0.0394],
        [0.1168, 0.2543],
        [0.0129, 0.3474],
        [0.0982, 0.3983],
        [0.5344, 0.6848]])

Reshaped to (5, 4):
 tensor([[0.9532, 0.5883, 0.5531, 0.3851],
        [0.6855, 0.5814, 0.7410, 0.8357],
        [0.1497, 0.1235, 0.1092, 0.0394],
        [0.1168, 0.2543, 0.0129, 0.3474],
        [0.0982, 0.3983, 0.5344, 0.6848]])

Reshaped to (2, 10):
 tensor([[0.9532, 0.5883, 0.5531, 0.3851, 0.6855, 0.5814, 0.7410, 0.8357, 0.1497,
         0.1235],
        [0.1092, 0.0394, 0.1168, 0.2543, 0.0129, 0.3474, 0.0982, 0.3983, 0.5344,
         0.6848]])


b. From the original tensor, extract the first 5 rows. Extract the second column.

Using NumPy:

In [ ]:
# Slicing
first_5_rows = numpy_tensor[:5]
print("\nFirst 5 rows:\n", first_5_rows)

second_column = numpy_tensor[:, 1]
print("\nSecond column:\n", second_column)


First 5 rows:
 [[0.01988852 0.76194883]
 [0.26121562 0.0305798 ]
 [0.35899616 0.11214245]
 [0.48299571 0.92111591]
 [0.13989817 0.76237405]]

Second column:
 [0.76194883 0.0305798  0.11214245 0.92111591 0.76237405 0.88205753
 0.38815569 0.76256603 0.68498638 0.90412517]


Using PyTorch:

In [ ]:
# Slicing
first_5_rows = pytorch_tensor[:5]
print("\nFirst 5 rows:\n", first_5_rows)

second_column = pytorch_tensor[:, 1]
print("\nSecond column:\n", second_column)


First 5 rows:
 tensor([[0.5475, 0.6223],
        [0.9176, 0.5835],
        [0.9201, 0.8948],
        [0.4342, 0.1051],
        [0.4537, 0.3094]])

Second column:
 tensor([0.6223, 0.5835, 0.8948, 0.1051, 0.3094, 0.5119, 0.0781, 0.7239, 0.0072,
        0.4659])


### 5. Broadcasting and Reduction Operations

a. Broadcasting. Create a tensor A of shape (5, 1) and another tensor B of shape (1, 5). Perform element-wise addition between A and B.

Using NumPy:

In [ ]:
# Broadcasting
A = np.random.rand(5, 1)
B = np.random.rand(1, 5)
broadcasted_sum = A + B
print("Broadcasted Sum:\n", broadcasted_sum)

Broadcasted Sum:
 [[0.25539712 0.51548087 0.26235928 0.22837693 0.96010826]
 [0.79201031 1.05209405 0.79897247 0.76499012 1.49672145]
 [0.28555317 0.54563692 0.29251534 0.25853298 0.99026432]
 [0.44315357 0.70323732 0.45011573 0.41613338 1.14786471]
 [0.29670835 0.5567921  0.30367051 0.26968816 1.00141949]]


Using PyTorch:

In [ ]:
# Broadcasting
A = torch.rand(5, 1)
B = torch.rand(1, 5)
broadcasted_sum = A + B
print("Broadcasted Sum:\n", broadcasted_sum)

Broadcasted Sum:
 tensor([[0.8869, 1.0798, 0.6912, 0.7383, 0.7282],
        [1.2675, 1.4603, 1.0718, 1.1189, 1.1088],
        [1.0618, 1.2547, 0.8661, 0.9132, 0.9031],
        [0.8808, 1.0736, 0.6850, 0.7321, 0.7220],
        [0.9600, 1.1528, 0.7643, 0.8114, 0.8013]])


b. Reduction Operations. Compute the sum, mean, and max of a tensor along a specific dimension.

Using NumPy:

In [ ]:
# Reduction Operations
tensor          = np.random.rand(5, 5)
sum_along_dim0  = tensor.sum(axis=0)
mean_along_dim1 = tensor.mean(axis=1)
max_value       = tensor.max()

print("\nSum along dimension 0:\n", sum_along_dim0)
print("\nMean along dimension 1:\n", mean_along_dim1)
print("\nMax value in the tensor:", max_value)


Sum along dimension 0:
 [2.34459688 2.57112618 3.13675491 1.01721091 2.73420773]

Mean along dimension 1:
 [0.6114325  0.51050728 0.22903627 0.37020991 0.63959336]

Max value in the tensor: 0.9976718444219386


Using PyTorch:

In [ ]:
# Reduction Operations
tensor          = torch.rand(5, 5)
sum_along_dim0  = tensor.sum(dim=0)
mean_along_dim1 = tensor.mean(dim=1)
max_value       = tensor.max()

print("\nSum along dimension 0:\n", sum_along_dim0)
print("\nMean along dimension 1:\n", mean_along_dim1)
print("\nMax value in the tensor:", max_value)


Sum along dimension 0:
 tensor([2.5776, 1.9053, 2.4076, 3.4690, 3.8148])

Mean along dimension 1:
 tensor([0.4772, 0.4931, 0.6226, 0.5623, 0.6796])

Max value in the tensor: tensor(0.9563)


### 6. Tensor Concatenation and Stacking

a. Create three tensors of shape (3, 3) filled with random numbers. [Concatenate](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) them along the first dimension. [Stack](https://numpy.org/doc/stable/reference/generated/numpy.stack.html) them along a new dimension.


Using NumPy:

In [ ]:
tensor1 = np.random.rand(3, 3)
tensor2 = np.random.rand(3, 3)
tensor3 = np.random.rand(3, 3)

# Concatenation
concatenated = np.concatenate((tensor1, tensor2, tensor3), axis=0)
print("Concatenated Tensors:\n", concatenated)

# Stacking
stacked = np.stack((tensor1, tensor2, tensor3))
print("\nStacked Tensors:\n", stacked)

Concatenated Tensors:
 [[0.96888369 0.99670371 0.90690812]
 [0.56249197 0.5493229  0.23309168]
 [0.07864513 0.50302018 0.67775642]
 [0.24224476 0.03860706 0.33070882]
 [0.86661851 0.99453747 0.5151435 ]
 [0.94117264 0.74923384 0.44334829]
 [0.75736703 0.19391764 0.29807274]
 [0.21749401 0.96986494 0.24856445]
 [0.82223803 0.23500061 0.70011499]]

Stacked Tensors:
 [[[0.96888369 0.99670371 0.90690812]
  [0.56249197 0.5493229  0.23309168]
  [0.07864513 0.50302018 0.67775642]]

 [[0.24224476 0.03860706 0.33070882]
  [0.86661851 0.99453747 0.5151435 ]
  [0.94117264 0.74923384 0.44334829]]

 [[0.75736703 0.19391764 0.29807274]
  [0.21749401 0.96986494 0.24856445]
  [0.82223803 0.23500061 0.70011499]]]


Using PyTorch:

In [ ]:
tensor1 = torch.rand(3, 3)
tensor2 = torch.rand(3, 3)
tensor3 = torch.rand(3, 3)

# Concatenation
concatenated = torch.cat((tensor1, tensor2, tensor3), dim=0)
print("Concatenated Tensors:\n", concatenated)

# Stacking
stacked = torch.stack((tensor1, tensor2, tensor3))
print("\nStacked Tensors:\n", stacked)

Concatenated Tensors:
 tensor([[0.5620, 0.0847, 0.8362],
        [0.5864, 0.3441, 0.2411],
        [0.2479, 0.6066, 0.9349],
        [0.1812, 0.9151, 0.0532],
        [0.7352, 0.4854, 0.0770],
        [0.3118, 0.1528, 0.3485],
        [0.9149, 0.7006, 0.9450],
        [0.1363, 0.8862, 0.8000],
        [0.5798, 0.2319, 0.6646]])

Stacked Tensors:
 tensor([[[0.5620, 0.0847, 0.8362],
         [0.5864, 0.3441, 0.2411],
         [0.2479, 0.6066, 0.9349]],

        [[0.1812, 0.9151, 0.0532],
         [0.7352, 0.4854, 0.0770],
         [0.3118, 0.1528, 0.3485]],

        [[0.9149, 0.7006, 0.9450],
         [0.1363, 0.8862, 0.8000],
         [0.5798, 0.2319, 0.6646]]])
